<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PlatformTarget>x64</PlatformTarget>

		<AssemblyName>FanControl.LenovoYoga</AssemblyName>
		<RootNamespace>FanControl.LenovoYoga</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Management" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="FanControl.Plugins">
			<HintPath>lib\FanControl.Plugins.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

</Project>